### ISSUE TITLE
作者你好，我想问问这个项目怎么修改api和key 谢谢

### ISSUE THREAD

**Issue by maotuworkroom** [dfggmc/AiChat#1]

**Comment by XiaoFeng-QWQ** [comment]
修改
/js/main.js
apiUrl 常量数组即可

**Comment by XiaoFeng-QWQ** [comment]
e?

**Comment by maotuworkroom** [comment]
作者大大，我想接入openai api可是不知道怎么改

**Comment by XiaoFeng-QWQ** [comment]
我提供了这样的思路：
单独用PHP写一个站点用于请求openai api
然后在用我这个程序请求刚才用PHP创建的站点就行了

**Comment by XiaoFeng-QWQ** [comment]
那个PHP站点相当于中继站！
希望对你有所帮助😊

**Comment by XiaoFeng-QWQ** [comment]
具体可参阅
[使用说明](https://github.com/dfggmc/AiChat/wiki/%E7%A8%8B%E5%BA%8F%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3)

**Comment by XiaoFeng-QWQ** [comment]
> 作者大大，我想接入openai api可是不知道怎么改



> 作者大大，我想接入openai api可是不知道怎么改
